language: java
notifications:
  hipchat:
    rooms:
      secure: UJs9ETlP0ttDsAbNu05O5rnjodYykgc4EyEAMGcdAEZLsaNxfajbH+lEIDexDk8NLsXa86Zd+CB6AuYi9SGaFAtmN0u9WhZjGtdPQPUabawdW+370/om7gYDCg7Uz151btUUnIXKgr7gLHXls8camzAh3CgYlpwj3j4+XFJkZhtxAsHGjOLizqIpk/f3FeBdsm+GD6EDm/AMQ158e2XqK61xoXs2gUCfISDPMHDo9zKCYfDkcHHUlQ0m3kCNmHOHZCsO+zDVfrxxZ85fuf9IUU1gCOZ5Qe5jOhfNxTNvGhv7un3J1v1CWYPNuet5qekNlxgCc/lVYFRE26FKTX+4fXEQtWDIILD2ZPtcolgiWR/PIbYuDnhY/0IYDMEB/XG4WbCCCuG3gAG+rt6DDLWfg8byVvqPxJDk/5ONvWJAPiDEUfJ8bdd/dWlTLIvFT16AZviFAT06d/grf1oh2JZv/4DOQjAT04Vi8laqUtREzZGs8KVwJz/VnGkifMaUSzJ3AM+2Pv0grMnOzppkpuzgqaBJB2VgtWaUxsr/BNLINFaK/Dte/E4l1zT8Sz1nTMha1XiUk/LOUvkvUUvfC2q9P+bjC4D2Icr8BMvC6+g0/oCyXzjuwt9+k/jEOkaMha1ceLvekBRwz0Yi/a7PFxIRBggbvLUstv5C+0NXfPEs6oU=
deploy:
  provider: releases
  api_key:
    secure: HaLgQjTqegx0wexEexbBKB+D1DGwbiW7zQgLMpbA/d1PUQRLHMIZLNE8u1V5/4/qLSRqmp/VdLHwvSWbcc7dPrzNN09rwEb7HPLORkCvSHq6/pOgnJ1xIWU4CMjNewjxYS94AnQN+0+PFdFw7mqTuf6cz/IVCZxypCEzckziI220DLYBXBS9vNSko55979yhQv7U31vd/CJ63cp21qvemAcFncQr98FKq6JsbpMtOOjAqjvN/VPpnphhoV7DxbiKEMZ9ZePClg69HpZ+Q/o2qUm/BKd32ZmpZosTE27Gaj81TVnLeLfveeBRt0jTK4gisS5++t6AfK01DHGexT4hVgG34jkjQQX76imCMa+sd61Ixs2P4rVRl9zqJKFBlxoeOkdXhenLqDZL0c/jKYXXtIln6f24rnQ26t1L7zbdI2I0G+gS0aZfXAMSXoFioZCplydRkuuHrr/HOVmlBk7LF36cvXSbv2UVwATrNjOZs0Sd0fBxrOtnQ7l9g3vSufV59kHE/ic80Lrbn8Pphh3gRDsOrVGF/vHvz5Aho0kCxLwqoz6hajQ0kIVvfIz3kC2xITeFWYwYgUUupLUopj2GiIpOdcPhZJ/9Lr0+zr3cxW/l7orWwmuVT/Eo9JdyhX+GaYvRvNkU9x1A1VFF/R3AOc2eSDi+zmCASbqdA9vE/Zs=
  file: build/libs/xlr-ucd-plugin-1.0.0.jar
  skip_cleanup: true
  on:
    tags: true
    repo: xebialabs-community/xlr-ucd-plugin
