language: java
notifications:
  hipchat:
    rooms:
      secure: UJs9ETlP0ttDsAbNu05O5rnjodYykgc4EyEAMGcdAEZLsaNxfajbH+lEIDexDk8NLsXa86Zd+CB6AuYi9SGaFAtmN0u9WhZjGtdPQPUabawdW+370/om7gYDCg7Uz151btUUnIXKgr7gLHXls8camzAh3CgYlpwj3j4+XFJkZhtxAsHGjOLizqIpk/f3FeBdsm+GD6EDm/AMQ158e2XqK61xoXs2gUCfISDPMHDo9zKCYfDkcHHUlQ0m3kCNmHOHZCsO+zDVfrxxZ85fuf9IUU1gCOZ5Qe5jOhfNxTNvGhv7un3J1v1CWYPNuet5qekNlxgCc/lVYFRE26FKTX+4fXEQtWDIILD2ZPtcolgiWR/PIbYuDnhY/0IYDMEB/XG4WbCCCuG3gAG+rt6DDLWfg8byVvqPxJDk/5ONvWJAPiDEUfJ8bdd/dWlTLIvFT16AZviFAT06d/grf1oh2JZv/4DOQjAT04Vi8laqUtREzZGs8KVwJz/VnGkifMaUSzJ3AM+2Pv0grMnOzppkpuzgqaBJB2VgtWaUxsr/BNLINFaK/Dte/E4l1zT8Sz1nTMha1XiUk/LOUvkvUUvfC2q9P+bjC4D2Icr8BMvC6+g0/oCyXzjuwt9+k/jEOkaMha1ceLvekBRwz0Yi/a7PFxIRBggbvLUstv5C+0NXfPEs6oU=
deploy:
  provider: releases
  api_key:
    secure: hDegpCXCj9DYUfBEpu9v4ZoHhDOij/zunpo04GqMNjPuZ1CuxD61ceolzhvdPyRCxx34m9DRpt2YVNznOTwYwENsVNg1V5iI7T1ZmUfq7CUiOcCvfJabiqRj8V20Xm3szPgSdE3YmLoh/+ljPL5WNXhS/i0H2WYx2ARYoMwp+G4VCXnIBCF5pMPueGV63NNKcdhP6PL8Nq4ZevpZ628DsdVHI6Qp/xCUdQXkLv6qMo/7xxu9uQQAPoZr4HGcpY/z5LlWDghnjJYvFOq3r3CAznfdCJIkBzr2Kr9fTKswq7tpcg+FPCEpNWQmf9Pre48pfFSkaOFol1z4+FbjxCTP1Ya4QNXw0VS2/XAR95Mdzl8wvCAOnJ8X2dxLYXOyQ7L7JzB1Jf1zFemKmy7NtKmVkPcc0N+wV9hcApxuak4H4jQxPMWPrRlfpQJf6Cl5WFWqlX6w1NrB2k9uK5zAurUwvly5kDSU6Dmhrxec0SiVOy/5qsVq7vFPqRQkJqTQTDXcndzFaZIjvBilStkksM4szsT2lvpncZPHFf8dgIEePvk+yPDgD6nsqS3v9GyVDITkSruqBwijeTLa05fqmklfiDJ5vZHHj87HsMEL0KQwzkFM1luWsCs68cYamn4PnhGo6P88af1vufXKWPpTL/ZySBRmhlzrIo4rW/nEe8w0eMw=
  file: build/libs/xlr-ucd-plugin-1.5.0.jar
  skip_cleanup: true
  on:
    tags: true
    repo: xebialabs-community/xlr-ucd-plugin
